//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitor1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _switch {
            get {
                object obj = ResourceManager.GetObject("_switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;ConfigurationSchema&quot;
        ///    targetNamespace=&quot;http://tempuri.org/ConfigurationSchema.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://tempuri.org/ConfigurationSchema.xsd&quot;
        ///    xmlns:mstns=&quot;http://tempuri.org/ConfigurationSchema.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;monitor&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;title&quot; type=&quot;xs:string&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot; /&gt;       
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigurationSchema {
            get {
                return ResourceManager.GetString("ConfigurationSchema", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap generic {
            get {
                object obj = ResourceManager.GetObject("generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap router {
            get {
                object obj = ResourceManager.GetObject("router", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;monitor version=&quot;0.1&quot;&gt;
        ///  &lt;title&gt;AXA London&lt;/title&gt;
        ///  &lt;site&gt;
        ///    &lt;name&gt;Newgate&lt;/name&gt;
        ///    &lt;device&gt;
        ///      &lt;id&gt;0&lt;/id&gt;
        ///      &lt;name&gt;UK001CHLAN01&lt;/name&gt;
        ///      &lt;type&gt;Monitor1.DeviceSwitch&lt;/type&gt;
        ///      &lt;ipaddress&gt;10.128.8.1&lt;/ipaddress&gt;
        ///      &lt;x&gt;10&lt;/x&gt;
        ///      &lt;y&gt;10&lt;/y&gt;
        ///    &lt;/device&gt;
        ///    &lt;device&gt;
        ///      &lt;id&gt;1&lt;/id&gt;
        ///      &lt;name&gt;UK001SWLAN05&lt;/name&gt;
        ///      &lt;type&gt;Monitor1.DeviceSwitch&lt;/type&gt;
        ///      &lt;ipaddress&gt;10.128.8.216&lt;/ipaddress&gt;
        ///      &lt;x&gt;110&lt;/x&gt;
        ///      &lt;y&gt;10&lt;/y&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleConfiguration {
            get {
                return ResourceManager.GetString("SampleConfiguration", resourceCulture);
            }
        }
    }
}
